### ISSUE TITLE
Too much white contrast? [Resolved]

### ISSUE THREAD

**Issue by stone2forge** [jonsnow231/Minimal-Resources#1]
The buttons and toggle switches being pure #ffffff white makes it somewhat blinding to the lazy eye when browsing the options menu in Obsidian, I know we can customize the theme to our liking or that the theme is white/black high contrast by design, but I was wondering if this could be changed.

![image](https://github.com/jonsnow231/Minimal-Resources/assets/76193584/b3306fad-a7d7-418c-b460-cbae840012af)
![image](https://github.com/jonsnow231/Minimal-Resources/assets/76193584/52573ba5-9881-42ac-aea1-65d18c832096)
![image](https://github.com/jonsnow231/Minimal-Resources/assets/76193584/6c975ea5-c90e-4602-96af-2eca5a910639)

**Comment by jonsnow231** [comment]
Sure, updated the text-on-accent and nav-indentation-guide-color. Thanks for the suggestion. 

![image](https://github.com/jonsnow231/Minimal-Resources/assets/83853289/8e8dfce7-958f-47dd-bba2-9645f309afaa)
